version: '3.9'

services:
  web:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: node_app
    volumes:
      - ./Server:/app

    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      POSTGRES_DB: mdsdb
      POSTGRES_USER: mdsuser
      POSTGRES_PASSWORD: mdspasss
      POSTGRES_HOST: db
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
      - libreoffice
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mdsdb
      POSTGRES_USER: mdsuser
      POSTGRES_PASSWORD: mdspass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  libreoffice:
    image: ghcr.io/linuxserver/libreoffice:latest
    container_name: libreoffice
    command: >
      soffice --headless --nologo --nofirststartwizard
      --accept="socket,host=0.0.0.0,port=8100;urp;"
    ports:
      - "8100:8100"
    volumes:
      - ./shared:/data
    restart: unless-stopped

  client:
    build:
      context: ./Client
    container_name: react_app
    ports:
      - "5173:5173"
    volumes:
      - ./Client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data: